name: iocd-test
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set environments
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      run: 
        echo $RELEASE_VERSION
        echo ${{env.RELEASE_VERSION}}
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        role-to-assume: arn:aws:iam::222222222222:role/my-github-actions-role-prod
        role-duration-seconds: 900
        aws-region: us-west-2
    - name: Test AWS Creds
      run: aws sts get-caller-identity
