name: test-oidc
permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::123456789012:role/github-oidc
          role-duration-seconds: 900
          aws-region: us-west-2
      - name: Test AWS Creds
        run: aws sts get-caller-identity
